name: 'electron'

on:
  workflow_dispatch:
  push:
    branches:
      - release
      - electron

jobs:
  publish-electron:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            target: 'darwin'
            arch: 'x64'
          - platform: 'macos-latest'
            target: 'darwin'
            arch: 'arm64'
          - platform: 'ubuntu-22.04'
            target: 'linux'
            arch: 'x64'
          - platform: 'ubuntu-22.04'
            target: 'linux'
            arch: 'arm64'
          - platform: 'windows-latest'
            target: 'win32'
            arch: 'x64'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: install dependencies
        run: bun install
        env:
          BUN_CONFIG_REGISTRY: 'https://registry.npmjs.org/'

      - name: Build Electron
        run: bun run build:electron

      - name: Build distributable (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          bun add -D electron-builder
          bunx electron-builder --win --x64 --publish=never
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Build distributable (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          bun add -D electron-builder
          bunx electron-builder --${{ matrix.target }} --${{ matrix.arch }} --publish=never
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Build distributable (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libnotify4-dev libnss3 libxss1 libasound2
          bun add -D electron-builder
          bunx electron-builder --linux --x64 --publish=never
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KPA-${{ matrix.platform }}-${{ matrix.arch }}
          path: release/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: matrix.platform == 'windows-latest' || (matrix.platform == 'macos-latest' && matrix.arch == 'x64')
        with:
          tag_name: app-v${{ env.APP_VERSION }}
          name: KPA v${{ env.APP_VERSION }}
          body: '如果你是Windows用户且是小白，直接选下面的.exe文件进行安装。'
          draft: true
          prerelease: false
          files: |
            release/${{ matrix.target }}*/**/*
        env:
          APP_VERSION: ${{ steps.package.outputs.version }}
